import { CatalogManufacturer } from '@/types';

// ─── Netgear AV ─────────────────────────────────────────────────────────────

export const netgearCatalog: CatalogManufacturer = {
  id: 'netgear',
  displayName: 'Netgear AV',
  brandColor: '#4a90d9',
  website: 'https://www.netgear.com/av',
  products: [
    // M4250 Series — AV Line managed switches
    {
      modelId: 'netgear-m4250-10g2f-poeplus',
      modelName: 'M4250-10G2F-PoE+',
      category: 'network-switch',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: '1GbE PoE+', type: 'ethernet', direction: 'input', count: 8 },
        { label: 'SFP', type: 'sfp', direction: 'input', count: 2 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '8x 1GbE PoE+ ports',
        '2x SFP uplinks',
        '125 W PoE budget',
        'AV Line profile',
        'IGMP snooping',
        'Dante/AES67 optimized',
      ],
      description: 'Compact 10-port AV Line managed switch with 125 W PoE budget.',
    },
    {
      modelId: 'netgear-m4250-10g2xf-poeplusplus',
      modelName: 'M4250-10G2XF-PoE++',
      category: 'network-switch',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: '1GbE PoE++', type: 'ethernet', direction: 'input', count: 8 },
        { label: 'SFP+ 10G', type: 'sfp', direction: 'input', count: 2 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '8x 1GbE PoE++ ports',
        '2x SFP+ 10G uplinks',
        '240 W PoE budget',
        'AV Line profile',
        'IGMP snooping',
        'Dante/AES67 optimized',
      ],
      description: '10-port AV Line managed switch with 240 W PoE++ budget and 10G uplinks.',
    },
    {
      modelId: 'netgear-m4250-26g4f-poeplusplus',
      modelName: 'M4250-26G4F-PoE++',
      category: 'network-switch',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: '1GbE PoE++', type: 'ethernet', direction: 'input', count: 24 },
        { label: 'SFP+ 10G', type: 'sfp', direction: 'input', count: 4 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '24x 1GbE PoE++ ports',
        '4x SFP+ 10G uplinks',
        '480 W PoE budget',
        'AV Line profile',
        'IGMP snooping',
        'Dante/AES67 optimized',
      ],
      description: '28-port AV Line managed switch with 480 W PoE++ budget.',
    },
    {
      modelId: 'netgear-m4250-40g8f-poeplusplus',
      modelName: 'M4250-40G8F-PoE++',
      category: 'network-switch',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: '1GbE PoE++', type: 'ethernet', direction: 'input', count: 40 },
        { label: 'SFP+ 10G', type: 'sfp', direction: 'input', count: 8 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '40x 1GbE PoE++ ports',
        '8x SFP+ 10G uplinks',
        '960 W PoE budget',
        'AV Line profile',
        'IGMP snooping',
        'Dante/AES67 optimized',
      ],
      description: '48-port AV Line managed switch with 960 W PoE++ budget.',
    },
    {
      modelId: 'netgear-m4250-40g8xf-poeplusplus',
      modelName: 'M4250-40G8XF-PoE++',
      category: 'network-switch',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: '1GbE PoE++', type: 'ethernet', direction: 'input', count: 40 },
        { label: 'SFP+ 10G', type: 'sfp', direction: 'input', count: 8 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '40x 1GbE PoE++ ports',
        '8x SFP+ 10G uplinks',
        '2880 W PoE budget',
        'AV Line profile',
        'IGMP snooping',
        'Dante/AES67 optimized',
      ],
      description: '48-port AV Line managed switch with 2880 W ultra-high PoE++ budget.',
    },
    {
      modelId: 'netgear-m4250-16xf',
      modelName: 'M4250-16XF',
      category: 'network-switch',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'SFP+ 10G', type: 'sfp', direction: 'input', count: 16 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '16x SFP+ 10G fiber/copper ports',
        'AV Line profile',
        'IGMP snooping',
        'Dante/AES67 optimized',
      ],
      description: '16-port all-SFP+ 10G AV Line managed switch for aggregation.',
    },

    // M4300 Series — 10G spine/aggregation switches
    {
      modelId: 'netgear-m4300-24x',
      modelName: 'M4300-24X',
      category: 'network-switch',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'SFP+ 10G', type: 'sfp', direction: 'input', count: 24 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '24x 10GbE SFP+ ports',
        'IGMP snooping',
        'Dante/AES67 optimized',
        'Stacking support',
      ],
      description: '24-port 10GbE SFP+ managed switch for high-density AV aggregation.',
    },
    {
      modelId: 'netgear-m4300-48x',
      modelName: 'M4300-48X',
      category: 'network-switch',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'SFP+ 10G', type: 'sfp', direction: 'input', count: 48 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '48x 10GbE SFP+ ports',
        'IGMP snooping',
        'Dante/AES67 optimized',
        'Stacking support',
      ],
      description: '48-port 10GbE SFP+ managed switch for large AV infrastructure.',
    },
    {
      modelId: 'netgear-m4300-96x',
      modelName: 'M4300-96X',
      category: 'network-switch',
      rackUnits: 2,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'SFP+ 10G (modular)', type: 'sfp', direction: 'input', count: 96 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '96x 10G modular ports',
        'Modular chassis',
        'IGMP snooping',
        'Dante/AES67 optimized',
      ],
      description: '2RU modular 96-port 10G managed switch chassis.',
    },

    // M4350 Series — Latest generation
    {
      modelId: 'netgear-m4350-24g4xf',
      modelName: 'M4350-24G4XF',
      category: 'network-switch',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: '1GbE', type: 'ethernet', direction: 'input', count: 24 },
        { label: 'SFP+ 10G', type: 'sfp', direction: 'input', count: 4 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '24x 1GbE ports',
        '4x SFP+ 10G uplinks',
        'IGMP snooping',
        'Dante/AES67 optimized',
        'Latest-gen M4350 platform',
      ],
      description: '28-port M4350 managed switch with 10G uplinks.',
    },
    {
      modelId: 'netgear-m4350-48g4xf',
      modelName: 'M4350-48G4XF',
      category: 'network-switch',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: '1GbE', type: 'ethernet', direction: 'input', count: 48 },
        { label: 'SFP+ 10G', type: 'sfp', direction: 'input', count: 4 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '48x 1GbE ports',
        '4x SFP+ 10G uplinks',
        'IGMP snooping',
        'Dante/AES67 optimized',
        'Latest-gen M4350 platform',
      ],
      description: '52-port M4350 managed switch with 10G uplinks.',
    },
    {
      modelId: 'netgear-m4350-24x4v',
      modelName: 'M4350-24X4V',
      category: 'network-switch',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'SFP+ 10G', type: 'sfp', direction: 'input', count: 24 },
        { label: 'QSFP28 100G', type: 'sfp', direction: 'input', count: 4 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '24x SFP+ 10G ports',
        '4x QSFP28 100G uplinks',
        'IGMP snooping',
        'Dante/AES67 optimized',
        'Latest-gen M4350 platform',
      ],
      description: '28-port M4350 spine switch with 100G QSFP28 uplinks.',
    },
    {
      modelId: 'netgear-m4350-48g8xf',
      modelName: 'M4350-48G8XF',
      category: 'network-switch',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: '1GbE', type: 'ethernet', direction: 'input', count: 48 },
        { label: 'SFP+ 10G', type: 'sfp', direction: 'input', count: 8 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80 },
      features: [
        '48x 1GbE ports',
        '8x SFP+ 10G uplinks',
        'IGMP snooping',
        'Dante/AES67 optimized',
        'Latest-gen M4350 platform',
      ],
      description: '56-port M4350 managed switch with eight 10G uplinks.',
    },
  ],
};

// ─── Eaton UPS ───────────────────────────────────────────────────────────────

export const eatonCatalog: CatalogManufacturer = {
  id: 'eaton',
  displayName: 'Eaton',
  brandColor: '#1b5e20',
  website: 'https://www.eaton.com/ups',
  products: [
    {
      modelId: 'eaton-5px-g2-1500rt',
      modelName: '5PX G2 1500 RT',
      category: 'ups',
      rackUnits: 2,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + REST via Network-M2/M3 card',
      },
      features: [
        '1500 VA / 1350 W',
        'Line-interactive topology',
        'Runtime ~10 min at full load',
        'LCD status display',
        'USB + serial management',
      ],
      description: '2RU line-interactive UPS, 1500 VA/1350 W, suitable for small rack systems.',
    },
    {
      modelId: 'eaton-5px-g2-2200rt',
      modelName: '5PX G2 2200 RT',
      category: 'ups',
      rackUnits: 2,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + REST via Network-M2/M3 card',
      },
      features: [
        '2200 VA / 1950 W',
        'Line-interactive topology',
        'Runtime ~8 min at full load',
        'LCD status display',
        'USB + serial management',
      ],
      description: '2RU line-interactive UPS, 2200 VA/1950 W.',
    },
    {
      modelId: 'eaton-5px-g2-3000rt',
      modelName: '5PX G2 3000 RT',
      category: 'ups',
      rackUnits: 2,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + REST via Network-M2/M3 card',
      },
      features: [
        '3000 VA / 2700 W',
        'Line-interactive topology',
        'Runtime ~6 min at full load',
        'LCD status display',
        'USB + serial management',
      ],
      description: '2RU line-interactive UPS, 3000 VA/2700 W.',
    },
    {
      modelId: 'eaton-9px-3000rt',
      modelName: '9PX 3000 RT',
      category: 'ups',
      rackUnits: 2,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + REST via Network-M2/M3 card',
      },
      features: [
        '3000 VA / 2700 W',
        'Online double-conversion topology',
        'Runtime ~6 min at full load',
        'Graphical LCD',
        'Dual management card slots',
      ],
      description: '2RU online double-conversion UPS, 3000 VA/2700 W.',
    },
    {
      modelId: 'eaton-9px-6000rt',
      modelName: '9PX 6000 RT',
      category: 'ups',
      rackUnits: 3,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + REST via Network-M2/M3 card',
      },
      features: [
        '6000 VA / 5400 W',
        'Online double-conversion topology',
        'Runtime ~5 min at full load',
        'Graphical LCD',
        'Dual management card slots',
      ],
      description: '3RU online double-conversion UPS, 6000 VA/5400 W.',
    },
    {
      modelId: 'eaton-9px-11000rt',
      modelName: '9PX 11000 RT',
      category: 'ups',
      rackUnits: 6,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + REST via Network-M2/M3 card',
      },
      features: [
        '11000 VA / 10000 W',
        'Online double-conversion topology',
        'Runtime ~4 min at full load',
        'Graphical LCD',
        'Dual management card slots',
      ],
      description: '6RU online double-conversion UPS, 11 kVA/10 kW for large AV racks.',
    },
    {
      modelId: 'eaton-5p-1550rack',
      modelName: '5P 1550 Rack',
      category: 'ups',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + REST via Network-M2/M3 card',
      },
      features: [
        '1550 VA / 1100 W',
        'Line-interactive topology',
        'Runtime ~8 min at full load',
        'Compact 1RU',
        'USB management',
      ],
      description: 'Compact 1RU line-interactive UPS, 1550 VA/1100 W.',
    },
    {
      modelId: 'eaton-9sx-3000',
      modelName: '9SX 3000',
      category: 'ups',
      rackUnits: 2,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + REST via Network-M2/M3 card',
      },
      features: [
        '3000 VA / 2700 W',
        'Online double-conversion topology',
        'Runtime ~6 min at full load',
        'Energy Star certified',
        'LCD status display',
      ],
      description: '2RU online double-conversion UPS, 3000 VA/2700 W.',
    },
  ],
};

// ─── Toshiba UPS ─────────────────────────────────────────────────────────────

export const toshibaCatalog: CatalogManufacturer = {
  id: 'toshiba',
  displayName: 'Toshiba',
  brandColor: '#e60012',
  website: 'https://www.toshiba.com/taes/ups',
  products: [
    {
      modelId: 'toshiba-t1000-1kva',
      modelName: 'T1000 1kVA',
      category: 'ups',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: { protocol: 'snmp', defaultPort: 161 },
      features: [
        '1000 VA / 900 W',
        'Online double-conversion topology',
        'Runtime ~10 min at full load',
        'SNMP management card',
      ],
      description: '1RU online double-conversion UPS, 1000 VA/900 W.',
    },
    {
      modelId: 'toshiba-t1000-2kva',
      modelName: 'T1000 2kVA',
      category: 'ups',
      rackUnits: 2,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: { protocol: 'snmp', defaultPort: 161 },
      features: [
        '2000 VA / 1800 W',
        'Online double-conversion topology',
        'Runtime ~8 min at full load',
        'SNMP management card',
      ],
      description: '2RU online double-conversion UPS, 2000 VA/1800 W.',
    },
    {
      modelId: 'toshiba-t1000-3kva',
      modelName: 'T1000 3kVA',
      category: 'ups',
      rackUnits: 2,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: { protocol: 'snmp', defaultPort: 161 },
      features: [
        '3000 VA / 2700 W',
        'Online double-conversion topology',
        'Runtime ~6 min at full load',
        'SNMP management card',
      ],
      description: '2RU online double-conversion UPS, 3000 VA/2700 W.',
    },
    {
      modelId: 'toshiba-3000sp-6kva',
      modelName: '3000 SP 6kVA',
      category: 'ups',
      rackUnits: 4,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: { protocol: 'snmp', defaultPort: 161 },
      features: [
        '6000 VA / 5400 W',
        'Online double-conversion topology',
        'Runtime ~5 min at full load',
        'SNMP management card',
        'Redundant PSU option',
      ],
      description: '4RU online double-conversion UPS, 6000 VA/5400 W for critical AV loads.',
    },
  ],
};

// ─── Gude PDU ────────────────────────────────────────────────────────────────

export const gudeCatalog: CatalogManufacturer = {
  id: 'gude',
  displayName: 'Gude',
  brandColor: '#0277bd',
  website: 'https://www.gude.info',
  products: [
    {
      modelId: 'gude-epc-8021',
      modelName: 'Expert Power Control 8021',
      category: 'pdu',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 8 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/statusjson.js' },
      features: [
        '8 individually switched outlets',
        'Per-outlet metering',
        'Web UI + REST API',
        'Email/SNMP alerting',
      ],
      description: '1RU intelligent switched and metered PDU with 8 outlets.',
    },
    {
      modelId: 'gude-epc-8026',
      modelName: 'Expert Power Control 8026',
      category: 'pdu',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 12 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/statusjson.js' },
      features: [
        '12 individually switched outlets',
        'Per-outlet metering',
        'Web UI + REST API',
        'Email/SNMP alerting',
      ],
      description: '1RU intelligent switched and metered PDU with 12 outlets.',
    },
    {
      modelId: 'gude-epc-8045',
      modelName: 'Expert Power Control 8045',
      category: 'pdu',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 24 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/statusjson.js' },
      features: [
        '24 individually switched outlets',
        'Per-outlet metering',
        'Integrated environmental sensors (temp/humidity/airflow)',
        'Web UI + REST API',
        'Email/SNMP alerting',
      ],
      description: '1RU high-density 24-outlet switched/metered PDU with environmental sensors.',
    },
    {
      modelId: 'gude-epc-8226',
      modelName: 'Expert Power Control 8226',
      category: 'pdu',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 12 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/statusjson.js' },
      features: [
        '12 individually switched outlets',
        'Dual-circuit input',
        'Per-outlet metering',
        'Web UI + REST API',
        'Email/SNMP alerting',
      ],
      description: '1RU dual-circuit 12-outlet switched and metered PDU.',
    },
    {
      modelId: 'gude-epc-8291',
      modelName: 'Expert Power Control 8291',
      category: 'pdu',
      rackUnits: 0,
      formFactor: 'desktop',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 24 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/statusjson.js' },
      features: [
        '24 outlets — hybrid AC/DC support',
        '0U vertical mount',
        'Per-outlet switching and metering',
        'Flagship model',
        'Web UI + REST API',
        'Email/SNMP alerting',
      ],
      description: '0U vertical flagship PDU with 24 hybrid AC/DC outlets.',
    },
    {
      modelId: 'gude-esb-7213',
      modelName: 'Expert Sensor Box 7213',
      category: 'pdu',
      rackUnits: 1,
      formFactor: 'half-rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/statusjson.js' },
      features: [
        'Temperature sensor',
        'Humidity sensor',
        'Airflow sensor',
        'No power outlets',
        'Web UI + REST API',
        'Email/SNMP alerting',
      ],
      description: 'Half-rack environmental sensor unit — temperature, humidity, and airflow monitoring.',
    },
    {
      modelId: 'gude-enc-2302',
      modelName: 'Expert Net Control 2302',
      category: 'pdu',
      rackUnits: 1,
      formFactor: 'half-rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Relay Output', type: 'power', direction: 'output', count: 4 },
      ],
      connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/statusjson.js' },
      features: [
        '4 relay outputs for dry-contact switching',
        'Environmental monitoring inputs',
        'Web UI + REST API',
        'Email/SNMP alerting',
      ],
      description: 'Half-rack relay controller with 4 outputs and environmental monitoring.',
    },
  ],
};

// ─── Raritan PDU ─────────────────────────────────────────────────────────────

export const raritanCatalog: CatalogManufacturer = {
  id: 'raritan',
  displayName: 'Raritan',
  brandColor: '#6d4c41',
  website: 'https://www.raritan.com',
  products: [
    {
      modelId: 'raritan-px3-5190r',
      modelName: 'PX3-5190R',
      category: 'pdu',
      rackUnits: 0,
      formFactor: 'desktop',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 24 },
      ],
      connectionInfo: {
        protocol: 'rest',
        defaultPort: 443,
        notes: 'HTTPS REST API + SNMP fallback',
      },
      features: [
        '24 outlets — intelligent rack PDU',
        '0U vertical mount',
        'Per-outlet metering',
        'Environmental sensor support',
        'Cascading up to 16 units',
        'HTTPS REST + SNMP',
      ],
      description: '0U vertical intelligent PDU with 24 metered outlets and cascading support.',
    },
    {
      modelId: 'raritan-px3-5660r',
      modelName: 'PX3-5660R',
      category: 'pdu',
      rackUnits: 0,
      formFactor: 'desktop',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 42 },
      ],
      connectionInfo: {
        protocol: 'rest',
        defaultPort: 443,
        notes: 'HTTPS REST API + SNMP fallback',
      },
      features: [
        '42 outlets — 3-phase intelligent rack PDU',
        '0U vertical mount',
        'Per-outlet switching',
        'Per-outlet metering',
        'Environmental sensor support',
        'Cascading up to 16 units',
        'HTTPS REST + SNMP',
      ],
      description: '0U vertical 3-phase intelligent PDU with 42 switched/metered outlets.',
    },
    {
      modelId: 'raritan-px3-5902v',
      modelName: 'PX3-5902V',
      category: 'pdu',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 8 },
      ],
      connectionInfo: {
        protocol: 'rest',
        defaultPort: 443,
        notes: 'HTTPS REST API + SNMP fallback',
      },
      features: [
        '8 outlets — 1RU intelligent rack PDU',
        'Per-outlet metering',
        'Environmental sensor support',
        'HTTPS REST + SNMP',
      ],
      description: '1RU intelligent rack PDU with 8 metered outlets.',
    },
    {
      modelId: 'raritan-px4-5190r',
      modelName: 'PX4-5190R',
      category: 'pdu',
      rackUnits: 0,
      formFactor: 'desktop',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 24 },
      ],
      connectionInfo: {
        protocol: 'rest',
        defaultPort: 443,
        notes: 'HTTPS REST API + SNMP fallback',
      },
      features: [
        '24 outlets — next-gen intelligent rack PDU',
        '0U vertical mount',
        'Per-outlet metering',
        'WiFi + BLE management',
        'Environmental sensor support',
        'Cascading up to 16 units',
        'HTTPS REST + SNMP',
      ],
      description: '0U vertical next-gen PX4 intelligent PDU with 24 metered outlets, WiFi and BLE.',
    },
    {
      modelId: 'raritan-px4-5660r',
      modelName: 'PX4-5660R',
      category: 'pdu',
      rackUnits: 0,
      formFactor: 'desktop',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 42 },
      ],
      connectionInfo: {
        protocol: 'rest',
        defaultPort: 443,
        notes: 'HTTPS REST API + SNMP fallback',
      },
      features: [
        '42 outlets — next-gen 3-phase intelligent rack PDU',
        '0U vertical mount',
        'Per-outlet switching',
        'Per-outlet metering',
        'WiFi + BLE management',
        'Environmental sensor support',
        'Cascading up to 16 units',
        'HTTPS REST + SNMP',
      ],
      description: '0U vertical next-gen PX4 3-phase PDU with 42 switched/metered outlets, WiFi and BLE.',
    },
  ],
};

// ─── APC / Schneider Electric ─────────────────────────────────────────────────

export const apcCatalog: CatalogManufacturer = {
  id: 'apc',
  displayName: 'APC by Schneider Electric',
  brandColor: '#ff6f00',
  website: 'https://www.apc.com',
  products: [
    // Rack PDUs
    {
      modelId: 'apc-ap7900b',
      modelName: 'AP7900B',
      category: 'pdu',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 8 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + NMC REST API',
      },
      features: [
        '8 individually switched outlets',
        '15 A rated',
        '1RU form factor',
        'SNMP + NMC REST management',
        'Per-outlet switching',
      ],
      description: '1RU rack PDU with 8 switched outlets at 15 A.',
    },
    {
      modelId: 'apc-ap7901b',
      modelName: 'AP7901B',
      category: 'pdu',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 8 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + NMC REST API',
      },
      features: [
        '8 individually switched outlets',
        '20 A rated',
        '1RU form factor',
        'SNMP + NMC REST management',
        'Per-outlet switching',
      ],
      description: '1RU rack PDU with 8 switched outlets at 20 A.',
    },
    {
      modelId: 'apc-ap7920b',
      modelName: 'AP7920B',
      category: 'pdu',
      rackUnits: 0,
      formFactor: 'desktop',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 12 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + NMC REST API',
      },
      features: [
        '12 individually switched outlets',
        '16 A rated',
        '0U vertical mount',
        'SNMP + NMC REST management',
        'Per-outlet switching',
      ],
      description: '0U vertical rack PDU with 12 switched outlets at 16 A.',
    },
    {
      modelId: 'apc-ap8959na3',
      modelName: 'AP8959NA3',
      category: 'pdu',
      rackUnits: 0,
      formFactor: 'desktop',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 42 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + NMC REST API',
      },
      features: [
        '42 outlets — 3-phase metered-by-outlet',
        '0U vertical mount',
        'NetShelter 9000 series',
        'Per-outlet metering',
        'SNMP + NMC REST management',
      ],
      description: '0U vertical 3-phase NetShelter 9000 PDU with 42 metered-by-outlet outputs.',
    },

    // UPS units
    {
      modelId: 'apc-smt1500rm2u',
      modelName: 'SMT1500RM2U',
      category: 'ups',
      rackUnits: 2,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + NMC REST API',
      },
      features: [
        '1500 VA Smart-UPS',
        'Line-interactive topology',
        'Runtime ~11 min at full load',
        'LCD status display',
        'SmartConnect cloud management',
      ],
      description: '2RU Smart-UPS line-interactive, 1500 VA, with network management.',
    },
    {
      modelId: 'apc-srt3000rmxli',
      modelName: 'SRT3000RMXLI',
      category: 'ups',
      rackUnits: 2,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + NMC REST API',
      },
      features: [
        '3000 VA Smart-UPS',
        'Online double-conversion topology',
        'Runtime ~6 min at full load',
        'Graphical LCD',
        'SmartConnect cloud management',
        'External battery pack support',
      ],
      description: '2RU Smart-UPS online double-conversion, 3000 VA, with external battery support.',
    },
  ],
};

// ─── CyberPower ───────────────────────────────────────────────────────────────

export const cyberpowerCatalog: CatalogManufacturer = {
  id: 'cyberpower',
  displayName: 'CyberPower',
  brandColor: '#37474f',
  website: 'https://www.cyberpowersystems.com',
  products: [
    // Rack PDUs
    {
      modelId: 'cyberpower-pdu81005',
      modelName: 'PDU81005',
      category: 'pdu',
      rackUnits: 1,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 8 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + HTTP management',
      },
      features: [
        '8 individually switched outlets',
        'Per-outlet metering',
        '1RU form factor',
        'SNMP + HTTP management',
      ],
      description: '1RU switched and metered PDU with 8 outlets.',
    },
    {
      modelId: 'cyberpower-pdu81007',
      modelName: 'PDU81007',
      category: 'pdu',
      rackUnits: 0,
      formFactor: 'desktop',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 16 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + HTTP management',
      },
      features: [
        '16 outlets — switched metered-by-outlet (MBO)',
        '0U vertical mount',
        'Per-outlet switching and metering',
        'SNMP + HTTP management',
      ],
      description: '0U vertical 16-outlet switched MBO PDU with per-outlet control.',
    },
    {
      modelId: 'cyberpower-pdu83108',
      modelName: 'PDU83108',
      category: 'pdu',
      rackUnits: 0,
      formFactor: 'desktop',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Outlet', type: 'power', direction: 'output', count: 30 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + HTTP management',
      },
      features: [
        '30 outlets — 3-phase monitored PDU',
        '0U vertical mount',
        'Per-phase metering',
        'SNMP + HTTP management',
      ],
      description: '0U vertical 3-phase monitored PDU with 30 outlets.',
    },

    // UPS
    {
      modelId: 'cyberpower-ol3000rtxl2u',
      modelName: 'OL3000RTXL2U',
      category: 'ups',
      rackUnits: 2,
      formFactor: 'rack',
      defaultPorts: [
        { label: 'Management Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        { label: 'Power Output', type: 'power', direction: 'output', count: 1 },
      ],
      connectionInfo: {
        protocol: 'snmp',
        defaultPort: 161,
        notes: 'SNMP + HTTP management',
      },
      features: [
        '3000 VA online UPS',
        'Online double-conversion topology',
        'Runtime ~6 min at full load',
        'LCD display',
        'SNMP + HTTP management',
        'External battery pack support',
      ],
      description: '2RU online double-conversion UPS, 3000 VA, with external battery support.',
    },
  ],
};
