import { CatalogManufacturer } from '@/types';

export const CATALOG: CatalogManufacturer[] = [
  // ─── Brompton ───────────────────────────────────────────────
  {
    id: 'brompton',
    displayName: 'Brompton Technology',
    brandColor: '#4caf50',
    website: 'https://www.bromptontech.com',
    products: [
      {
        modelId: 'brompton-sx40',
        modelName: 'Tessera SX40',
        category: 'led-processor',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 2 },
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 1 },
          { label: 'Ethernet Out', type: 'ethernet', direction: 'output', count: 4 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['4K input', 'DynaCal', 'DarkMagic', 'PureTone', '10-bit processing'],
        description: 'Flagship LED processor with 4K input and advanced processing.',
      },
      {
        modelId: 'brompton-s8',
        modelName: 'Tessera S8',
        category: 'led-processor',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 1 },
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 1 },
          { label: 'Ethernet Out', type: 'ethernet', direction: 'output', count: 2 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['DynaCal', 'DarkMagic', 'PureTone', '8 outputs'],
        description: 'Compact LED processor for small-to-medium LED walls.',
      },
      {
        modelId: 'brompton-xd',
        modelName: 'Tessera XD',
        category: 'led-processor',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'Fiber In', type: 'sfp', direction: 'input', count: 2 },
          { label: 'Ethernet Out', type: 'ethernet', direction: 'output', count: 16 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['16 Ethernet outputs', 'Distribution unit', 'SFP fiber input'],
        description: '10G distribution unit for large-scale LED walls.',
      },
    ],
  },

  // ─── Novastar ───────────────────────────────────────────────
  {
    id: 'novastar',
    displayName: 'Novastar',
    brandColor: '#f44336',
    website: 'https://www.novastar.tech',
    products: [
      {
        modelId: 'novastar-mctrl4k',
        modelName: 'MCTRL 4K',
        category: 'led-processor',
        rackUnits: 2,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 1 },
          { label: 'DP In', type: 'displayport', direction: 'input', count: 1 },
          { label: 'DVI In', type: 'dvi', direction: 'input', count: 1 },
          { label: 'Ethernet Out', type: 'ethernet', direction: 'output', count: 16 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['4K@60Hz input', '16 Ethernet outputs', '10.4M pixel capacity'],
        description: 'Professional 4K LED controller with massive pixel capacity.',
      },
      {
        modelId: 'novastar-mctrl660',
        modelName: 'MCTRL 660',
        category: 'led-processor',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 1 },
          { label: 'DVI In', type: 'dvi', direction: 'input', count: 1 },
          { label: 'Ethernet Out', type: 'ethernet', direction: 'output', count: 6 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['1920x1200 input', '6 Ethernet outputs', '1.3M pixel capacity'],
      },
      {
        modelId: 'novastar-vx1000',
        modelName: 'VX1000',
        category: 'led-processor',
        rackUnits: 2,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 2 },
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 2 },
          { label: 'DP In', type: 'displayport', direction: 'input', count: 2 },
          { label: 'Ethernet Out', type: 'ethernet', direction: 'output', count: 20 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['All-in-one controller', '4K processing', 'Layer management', '20 outputs'],
        description: 'All-in-one video controller with advanced processing and scaling.',
      },
      {
        modelId: 'novastar-vx400',
        modelName: 'VX400',
        category: 'led-processor',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 2 },
          { label: 'DP In', type: 'displayport', direction: 'input', count: 1 },
          { label: 'Ethernet Out', type: 'ethernet', direction: 'output', count: 4 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['4K input', '4 Ethernet outputs', 'Compact 1RU'],
      },
      {
        modelId: 'novastar-vx600',
        modelName: 'VX600',
        category: 'led-processor',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 2 },
          { label: 'DP In', type: 'displayport', direction: 'input', count: 1 },
          { label: 'Ethernet Out', type: 'ethernet', direction: 'output', count: 6 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['4K input', '6 Ethernet outputs', 'Layer management'],
      },
    ],
  },

  // ─── Barco ──────────────────────────────────────────────────
  {
    id: 'barco',
    displayName: 'Barco',
    brandColor: '#00bcd4',
    website: 'https://www.barco.com',
    products: [
      {
        modelId: 'barco-e2',
        modelName: 'E2',
        category: 'video-processor',
        rackUnits: 4,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 8 },
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 4 },
          { label: 'DP In', type: 'displayport', direction: 'input', count: 4 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 8 },
        ],
        connectionInfo: { protocol: 'json-rpc', defaultPort: 9000, notes: 'JSON-RPC 2.0' },
        features: ['4K processing', 'Multi-screen', 'PiP', 'Seamless switching', '16 inputs'],
        description: 'Flagship event processor for multi-screen presentations.',
      },
      {
        modelId: 'barco-s3-4k',
        modelName: 'S3-4K',
        category: 'video-processor',
        rackUnits: 2,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 4 },
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 4 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 4 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 2 },
        ],
        connectionInfo: { protocol: 'json-rpc', defaultPort: 9000 },
        features: ['4K60', 'Tri-combo', '8 inputs', 'ScreenPro heritage'],
      },
      {
        modelId: 'barco-pds902',
        modelName: 'PDS-902 3G',
        category: 'video-processor',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 4 },
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 2 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 2 },
        ],
        connectionInfo: { protocol: 'json-rpc', defaultPort: 9000 },
        features: ['Seamless switching', '3G-SDI', '6 inputs', 'Compact 1RU'],
      },
    ],
  },

  // ─── Disguise ───────────────────────────────────────────────
  {
    id: 'disguise',
    displayName: 'disguise',
    brandColor: '#e91e63',
    website: 'https://www.disguise.one',
    products: [
      {
        modelId: 'disguise-gx3',
        modelName: 'gx 3',
        category: 'media-server',
        rackUnits: 4,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 4 },
          { label: 'DP Out', type: 'displayport', direction: 'output', count: 4 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 6 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['4x GPU outputs', 'Notch integration', 'Generative content', 'MR/XR'],
        description: 'Top-tier media server for large-scale generative shows.',
      },
      {
        modelId: 'disguise-gx2c',
        modelName: 'gx 2c',
        category: 'media-server',
        rackUnits: 4,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 4 },
          { label: 'DP Out', type: 'displayport', direction: 'output', count: 4 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 6 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['Compact gx', '4x GPU outputs', 'Notch', 'MR/XR capable'],
      },
      {
        modelId: 'disguise-vx4',
        modelName: 'vx 4',
        category: 'media-server',
        rackUnits: 4,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 4 },
          { label: 'DP Out', type: 'displayport', direction: 'output', count: 4 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 6 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['4x 4K outputs', 'HAP/NotchLC playback', 'NDI', 'Video touring'],
      },
      {
        modelId: 'disguise-solo',
        modelName: 'solo',
        category: 'media-server',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 2 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['Compact 1RU', 'Single output', 'Entry level', 'Web UI'],
      },
      {
        modelId: 'disguise-rx2',
        modelName: 'rx II',
        category: 'media-server',
        rackUnits: 2,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 4 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 4 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['Render engine', 'SMPTE 2110', 'Cluster rendering', 'xR render node'],
      },
    ],
  },

  // ─── Blackmagic Design ──────────────────────────────────────
  {
    id: 'blackmagic',
    displayName: 'Blackmagic Design',
    brandColor: '#607d8b',
    website: 'https://www.blackmagicdesign.com',
    products: [
      {
        modelId: 'bmd-vh40',
        modelName: 'Smart Videohub 40x40',
        category: 'matrix-switcher',
        rackUnits: 4,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 40 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 40 },
        ],
        connectionInfo: { protocol: 'tcp', defaultPort: 9990 },
        features: ['12G-SDI', '40x40 routing', 'RS-422 deck control'],
        description: 'Large-format SDI router for broadcast and live production.',
      },
      {
        modelId: 'bmd-vh20',
        modelName: 'Smart Videohub 20x20',
        category: 'matrix-switcher',
        rackUnits: 2,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 20 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 20 },
        ],
        connectionInfo: { protocol: 'tcp', defaultPort: 9990 },
        features: ['12G-SDI', '20x20 routing'],
      },
      {
        modelId: 'bmd-vh12',
        modelName: 'Smart Videohub 12x12',
        category: 'matrix-switcher',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 12 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 12 },
        ],
        connectionInfo: { protocol: 'tcp', defaultPort: 9990 },
        features: ['6G-SDI', '12x12 routing', 'Compact 1RU'],
      },
      {
        modelId: 'bmd-atem-constellation-8k',
        modelName: 'ATEM Constellation 8K',
        category: 'production-switcher',
        rackUnits: 4,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 40 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 24 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80 },
        features: ['8K switching', '40 inputs', 'SuperSource', 'Fairlight audio'],
        description: 'Flagship production switcher with 8K capability.',
      },
      {
        modelId: 'bmd-atem-4me',
        modelName: 'ATEM 4 M/E Constellation HD',
        category: 'production-switcher',
        rackUnits: 4,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 20 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 12 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80 },
        features: ['4 M/E buses', '20 inputs', 'SuperSource', 'DVE'],
      },
      {
        modelId: 'bmd-hyperdeck-4k-pro',
        modelName: 'HyperDeck Studio 4K Pro',
        category: 'recorder',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 2 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 2 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/control/api/v1' },
        features: ['4K ProRes recording', 'H.265', 'Dual SSD slots'],
      },
      {
        modelId: 'bmd-teranex-sdi-hdmi',
        modelName: 'Teranex Mini SDI to HDMI 12G',
        category: 'converter',
        rackUnits: 1,
        formFactor: 'half-rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 1 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/control/api/v1' },
        features: ['12G-SDI', 'HDR support', 'Front panel LCD'],
      },
      {
        modelId: 'bmd-teranex-hdmi-sdi',
        modelName: 'Teranex Mini HDMI to SDI 12G',
        category: 'converter',
        rackUnits: 1,
        formFactor: 'half-rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 1 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/control/api/v1' },
        features: ['12G-SDI output', 'HDR passthrough'],
      },
    ],
  },

  // ─── Lightware ──────────────────────────────────────────────
  {
    id: 'lightware',
    displayName: 'Lightware',
    brandColor: '#ff9800',
    website: 'https://www.lightware.com',
    products: [
      {
        modelId: 'lw-mx2-16x16',
        modelName: 'MX2-16x16-HDMI20',
        category: 'matrix-switcher',
        rackUnits: 2,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 16 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 16 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['HDMI 2.0', '4K60 4:4:4', '16x16 routing', 'EDID management'],
        description: 'Professional HDMI 2.0 matrix switcher.',
      },
      {
        modelId: 'lw-mx2-8x8',
        modelName: 'MX2-8x8-HDMI20',
        category: 'matrix-switcher',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 8 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 8 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['HDMI 2.0', '4K60', '8x8 routing', 'Compact 1RU'],
      },
      {
        modelId: 'lw-mmx6x2-ht',
        modelName: 'MMX6x2-HT200',
        category: 'matrix-switcher',
        rackUnits: 1,
        formFactor: 'half-rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 4 },
          { label: 'HDBaseT In', type: 'hdbaset', direction: 'input', count: 2 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
          { label: 'HDBaseT Out', type: 'hdbaset', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['6x2 matrix', 'HDBaseT', 'Audio de-embedding'],
      },
      {
        modelId: 'lw-ubex-pro20',
        modelName: 'UBEX-Pro20-HDMI-F100',
        category: 'fiber-extender',
        rackUnits: 1,
        formFactor: 'half-rack',
        defaultPorts: [
          { label: 'HDMI', type: 'hdmi', direction: 'input', count: 1 },
          { label: 'SFP', type: 'sfp', direction: 'output', count: 2 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['4K60 over fiber', 'USB 2.0 extension', 'Zero-compression'],
      },
      {
        modelId: 'lw-vinx-120',
        modelName: 'VINX-120-HDMI-ENC',
        category: 'encoder-decoder',
        rackUnits: 1,
        formFactor: 'half-rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['AV-over-IP encoder', '4K60', '1GbE', 'Low latency'],
      },
    ],
  },

  // ─── AJA ────────────────────────────────────────────────────
  {
    id: 'aja',
    displayName: 'AJA Video Systems',
    brandColor: '#ffc107',
    website: 'https://www.aja.com',
    products: [
      {
        modelId: 'aja-kumo-3232',
        modelName: 'KUMO 3232-12G',
        category: 'matrix-switcher',
        rackUnits: 2,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 32 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 32 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80 },
        features: ['12G-SDI', '32x32 routing', 'Embedded web UI'],
        description: 'Compact 12G-SDI router with web control.',
      },
      {
        modelId: 'aja-kumo-1616',
        modelName: 'KUMO 1616-12G',
        category: 'matrix-switcher',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 16 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 16 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80 },
        features: ['12G-SDI', '16x16 routing', 'Compact 1RU'],
      },
      {
        modelId: 'aja-kumo-1604',
        modelName: 'KUMO 1604',
        category: 'matrix-switcher',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 16 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 4 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80 },
        features: ['3G-SDI', '16x4 routing', 'Compact 1RU'],
      },
      {
        modelId: 'aja-ki-pro-ultra-12g',
        modelName: 'Ki Pro Ultra 12G',
        category: 'recorder',
        rackUnits: 2,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 4 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 4 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80 },
        features: ['4K/UHD recording', 'Multi-channel', 'Apple ProRes', '12G-SDI'],
      },
      {
        modelId: 'aja-fs-hdr',
        modelName: 'FS-HDR',
        category: 'converter',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 4 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 4 },
          { label: 'Fiber In', type: 'sfp', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80 },
        features: ['HDR/WCG conversion', 'Frame sync', '12G-SDI', 'Colorfront engine'],
      },
      {
        modelId: 'aja-hi5-12g',
        modelName: 'Hi5-12G',
        category: 'converter',
        rackUnits: 1,
        formFactor: 'portable',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 1 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80 },
        features: ['12G-SDI to HDMI 2.0', '4K60', 'Mini converter'],
      },
    ],
  },

  // ─── Panasonic ──────────────────────────────────────────────
  {
    id: 'panasonic',
    displayName: 'Panasonic',
    brandColor: '#0068b5',
    website: 'https://www.panasonic.com',
    products: [
      {
        modelId: 'panasonic-ue160',
        modelName: 'AW-UE160',
        category: 'ptz-camera',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 1 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'cgi', defaultPort: 80, apiBasePath: '/cgi-bin' },
        features: ['4K60', '20x optical zoom', 'NDI|HX', '12G-SDI', 'Free-D tracking'],
        description: 'Flagship 4K PTZ camera with NDI and Free-D tracking.',
      },
      {
        modelId: 'panasonic-ue150',
        modelName: 'AW-UE150',
        category: 'ptz-camera',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 1 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'cgi', defaultPort: 80, apiBasePath: '/cgi-bin' },
        features: ['4K', '20x optical zoom', 'NDI|HX', '12G-SDI'],
      },
      {
        modelId: 'panasonic-ue100',
        modelName: 'AW-UE100',
        category: 'ptz-camera',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 1 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'cgi', defaultPort: 80, apiBasePath: '/cgi-bin' },
        features: ['4K', '24x zoom', 'NDI|HX2', 'SRT streaming'],
      },
      {
        modelId: 'panasonic-he145',
        modelName: 'AW-HE145',
        category: 'ptz-camera',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 1 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'cgi', defaultPort: 80, apiBasePath: '/cgi-bin' },
        features: ['1080p60', '20x zoom', '3G-SDI', 'PoE+'],
      },
      {
        modelId: 'panasonic-rp150',
        modelName: 'AW-RP150',
        category: 'camera-controller',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'Ethernet', type: 'ethernet', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'cgi', defaultPort: 80, apiBasePath: '/cgi-bin' },
        features: ['100-camera control', 'Touchscreen', 'IP connection', 'Joystick'],
      },
    ],
  },

  // ─── Sony ───────────────────────────────────────────────────
  {
    id: 'sony',
    displayName: 'Sony',
    brandColor: '#000000',
    website: 'https://pro.sony',
    products: [
      {
        modelId: 'sony-srg-x400',
        modelName: 'SRG-X400',
        category: 'ptz-camera',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'visca', defaultPort: 52381, notes: 'VISCA over IP, REST /command fallback' },
        features: ['4K30', '40x zoom', 'NDI|HX', 'PoE+', 'VISCA/IP'],
        description: 'Compact 4K PTZ camera with 40x zoom.',
      },
      {
        modelId: 'sony-srg-x120',
        modelName: 'SRG-X120',
        category: 'ptz-camera',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'visca', defaultPort: 52381 },
        features: ['4K30', '12x zoom', 'NDI|HX', 'PoE+'],
      },
      {
        modelId: 'sony-srg-a40',
        modelName: 'SRG-A40',
        category: 'ptz-camera',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'visca', defaultPort: 52381 },
        features: ['4K60', '30x zoom', 'AI framing', 'NDI|HX3'],
      },
      {
        modelId: 'sony-brc-x400',
        modelName: 'BRC-X400',
        category: 'ptz-camera',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 1 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'visca', defaultPort: 52381 },
        features: ['4K', '20x zoom', 'NDI|HX', 'Free-D compatible'],
      },
      {
        modelId: 'sony-rm-ip500',
        modelName: 'RM-IP500',
        category: 'camera-controller',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'Ethernet', type: 'ethernet', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'visca', defaultPort: 52381 },
        features: ['100-camera control', 'Joystick', 'IP/serial', 'Preset recall'],
      },
    ],
  },

  // ─── Christie ───────────────────────────────────────────────
  {
    id: 'christie',
    displayName: 'Christie',
    brandColor: '#c62828',
    website: 'https://www.christiedigital.com',
    products: [
      {
        modelId: 'christie-griffyn-4k32',
        modelName: 'Griffyn 4K32-RGB',
        category: 'projector',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 2 },
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 2 },
          { label: 'DP In', type: 'displayport', direction: 'input', count: 1 },
          { label: 'HDBaseT In', type: 'hdbaset', direction: 'input', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api', notes: 'PJLink fallback' },
        features: ['4K', '32,000 lumens', 'RGB laser', 'Omnidirectional'],
        description: 'Pure RGB laser projector for large-venue installations.',
      },
      {
        modelId: 'christie-d4k40-rgb',
        modelName: 'D4K40-RGB',
        category: 'projector',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 2 },
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 2 },
          { label: 'DP In', type: 'displayport', direction: 'input', count: 1 },
          { label: 'HDBaseT In', type: 'hdbaset', direction: 'input', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['4K', '40,000 lumens', 'RGB laser', 'CoolBlue'],
      },
      {
        modelId: 'christie-crimson-hd31',
        modelName: 'Crimson HD31',
        category: 'projector',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 2 },
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 1 },
          { label: 'HDBaseT In', type: 'hdbaset', direction: 'input', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['HD', '31,000 lumens', 'Laser phosphor', 'Omnidirectional'],
      },
    ],
  },

  // ─── Epson ──────────────────────────────────────────────────
  {
    id: 'epson',
    displayName: 'Epson',
    brandColor: '#003399',
    website: 'https://www.epson.com',
    products: [
      {
        modelId: 'epson-pu2220b',
        modelName: 'EB-PU2220B',
        category: 'projector',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 2 },
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 1 },
          { label: 'HDBaseT In', type: 'hdbaset', direction: 'input', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'cgi', defaultPort: 80, notes: 'ESC/VP.net TCP :3629 fallback' },
        features: ['WUXGA', '20,000 lumens', 'Laser', 'Edge blending'],
        description: 'High-brightness laser projector for venues and staging.',
      },
      {
        modelId: 'epson-l30000u',
        modelName: 'EB-L30000U',
        category: 'projector',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 2 },
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 2 },
          { label: 'HDBaseT In', type: 'hdbaset', direction: 'input', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'cgi', defaultPort: 80 },
        features: ['WUXGA', '30,000 lumens', '4K enhancement', 'Laser'],
      },
      {
        modelId: 'epson-l12000q',
        modelName: 'Pro L12000Q',
        category: 'projector',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 2 },
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 1 },
          { label: 'HDBaseT In', type: 'hdbaset', direction: 'input', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'cgi', defaultPort: 80 },
        features: ['4K native', '12,000 lumens', 'Laser', 'Edge blending'],
      },
    ],
  },

  // ─── Shure ──────────────────────────────────────────────────
  {
    id: 'shure',
    displayName: 'Shure',
    brandColor: '#1a237e',
    website: 'https://www.shure.com',
    products: [
      {
        modelId: 'shure-ulxd4q',
        modelName: 'ULXD4Q',
        category: 'wireless-microphone',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'XLR Out', type: 'analog-audio', direction: 'output', count: 4 },
          { label: 'AES Out', type: 'aes-ebu', direction: 'output', count: 2 },
          { label: 'Dante', type: 'dante', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api/v1.0' },
        features: ['Quad receiver', 'Dante output', 'Networked control', 'High density'],
        description: 'Quad-channel UHF-D wireless receiver with Dante.',
      },
      {
        modelId: 'shure-ulxd4d',
        modelName: 'ULXD4D',
        category: 'wireless-microphone',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'XLR Out', type: 'analog-audio', direction: 'output', count: 2 },
          { label: 'AES Out', type: 'aes-ebu', direction: 'output', count: 1 },
          { label: 'Dante', type: 'dante', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api/v1.0' },
        features: ['Dual receiver', 'Dante output', 'Networked control'],
      },
      {
        modelId: 'shure-p300',
        modelName: 'P300-IMX',
        category: 'audio-dsp',
        rackUnits: 1,
        formFactor: 'half-rack',
        defaultPorts: [
          { label: 'Dante', type: 'dante', direction: 'input', count: 1 },
          { label: 'Analog Out', type: 'analog-audio', direction: 'output', count: 1 },
          { label: 'USB', type: 'usb', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api/v1.0' },
        features: ['IntelliMix DSP', 'AEC', 'Dante 10-ch', 'USB audio'],
      },
      {
        modelId: 'shure-mxa920',
        modelName: 'MXA920',
        category: 'audio-interface',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'Dante', type: 'dante', direction: 'output', count: 1 },
          { label: 'Ethernet PoE', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api/v1.0' },
        features: ['Ceiling array mic', 'Autofocus beamforming', 'Dante', 'PoE'],
      },
      {
        modelId: 'shure-ani22',
        modelName: 'ANI22',
        category: 'audio-interface',
        rackUnits: 1,
        formFactor: 'half-rack',
        defaultPorts: [
          { label: 'XLR In', type: 'analog-audio', direction: 'input', count: 2 },
          { label: 'XLR Out', type: 'analog-audio', direction: 'output', count: 2 },
          { label: 'Dante', type: 'dante', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api/v1.0' },
        features: ['2-in/2-out Dante interface', 'PoE powered', 'Networked'],
      },
    ],
  },

  // ─── QSC ────────────────────────────────────────────────────
  {
    id: 'qsc',
    displayName: 'QSC',
    brandColor: '#2e7d32',
    website: 'https://www.qsc.com',
    products: [
      {
        modelId: 'qsc-core110f',
        modelName: 'Core 110f',
        category: 'audio-dsp',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'Dante', type: 'dante', direction: 'input', count: 1 },
          { label: 'Dante', type: 'dante', direction: 'output', count: 1 },
          { label: 'USB', type: 'usb', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 2 },
        ],
        connectionInfo: { protocol: 'json-rpc', defaultPort: 1710, notes: 'Q-SYS JSON-RPC' },
        features: ['Q-SYS Core', '64 Dante channels', 'UCI', 'Scripting engine'],
        description: 'Compact Q-SYS processing core for Dante networks.',
      },
      {
        modelId: 'qsc-core510i',
        modelName: 'Core 510i',
        category: 'audio-dsp',
        rackUnits: 2,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'Analog In', type: 'analog-audio', direction: 'input', count: 8 },
          { label: 'Analog Out', type: 'analog-audio', direction: 'output', count: 8 },
          { label: 'AES In', type: 'aes-ebu', direction: 'input', count: 4 },
          { label: 'AES Out', type: 'aes-ebu', direction: 'output', count: 4 },
          { label: 'Dante', type: 'dante', direction: 'input', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 2 },
        ],
        connectionInfo: { protocol: 'json-rpc', defaultPort: 1710 },
        features: ['Q-SYS Core', '256 Dante channels', 'Integrated I/O', 'UCI'],
      },
      {
        modelId: 'qsc-cx-q',
        modelName: 'CX-Q 8K8',
        category: 'amplifier',
        rackUnits: 2,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'Dante', type: 'dante', direction: 'input', count: 1 },
          { label: 'Speaker Out', type: 'analog-audio', direction: 'output', count: 8 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'json-rpc', defaultPort: 1710 },
        features: ['8-channel amp', 'Q-SYS native', 'Dante input', '8000W total'],
      },
      {
        modelId: 'qsc-nv32h',
        modelName: 'NV-32-H',
        category: 'encoder-decoder',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 1 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
          { label: 'USB', type: 'usb', direction: 'output', count: 4 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'json-rpc', defaultPort: 1710 },
        features: ['AV-over-IP', 'Q-SYS native', 'USB extension', '4K60'],
      },
    ],
  },

  // ─── Audinate ───────────────────────────────────────────────
  {
    id: 'audinate',
    displayName: 'Audinate',
    brandColor: '#00838f',
    website: 'https://www.audinate.com',
    products: [
      {
        modelId: 'audinate-avio-analog-in',
        modelName: 'AVIO Analog Input',
        category: 'audio-interface',
        rackUnits: 0,
        formFactor: 'portable',
        defaultPorts: [
          { label: 'XLR In', type: 'analog-audio', direction: 'input', count: 2 },
          { label: 'Dante', type: 'dante', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'mdns', defaultPort: 8080, notes: 'mDNS discovery, REST fallback' },
        features: ['2-ch analog to Dante', 'PoE powered', 'Ultra-low latency'],
        description: 'Compact 2-channel analog to Dante adapter.',
      },
      {
        modelId: 'audinate-avio-analog-out',
        modelName: 'AVIO Analog Output',
        category: 'audio-interface',
        rackUnits: 0,
        formFactor: 'portable',
        defaultPorts: [
          { label: 'Dante', type: 'dante', direction: 'input', count: 1 },
          { label: 'XLR Out', type: 'analog-audio', direction: 'output', count: 2 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'mdns', defaultPort: 8080 },
        features: ['2-ch Dante to analog', 'PoE powered', 'Ultra-low latency'],
      },
      {
        modelId: 'audinate-avio-usb',
        modelName: 'AVIO USB',
        category: 'audio-interface',
        rackUnits: 0,
        formFactor: 'portable',
        defaultPorts: [
          { label: 'Dante', type: 'dante', direction: 'input', count: 1 },
          { label: 'Dante', type: 'dante', direction: 'output', count: 1 },
          { label: 'USB', type: 'usb', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'mdns', defaultPort: 8080 },
        features: ['USB to Dante bridge', 'PoE powered', 'Bidirectional'],
      },
    ],
  },

  // ─── Luminex ────────────────────────────────────────────────
  {
    id: 'luminex',
    displayName: 'Luminex',
    brandColor: '#6a1b9a',
    website: 'https://www.luminex.be',
    products: [
      {
        modelId: 'luminex-gc30i',
        modelName: 'GigaCore 30i',
        category: 'network-switch',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 24 },
          { label: 'SFP', type: 'sfp', direction: 'input', count: 6 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['30-port', 'AVB/TSN', 'Dante optimized', 'Redundant PSU'],
        description: 'AV-grade managed Ethernet switch for Dante and AES67.',
      },
      {
        modelId: 'luminex-gc16xt',
        modelName: 'GigaCore 16Xt',
        category: 'network-switch',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 12 },
          { label: 'SFP', type: 'sfp', direction: 'input', count: 4 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['16-port', 'AVB/TSN', 'Touring grade', 'PoE optional'],
      },
      {
        modelId: 'luminex-gc14r',
        modelName: 'GigaCore 14R',
        category: 'network-switch',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 12 },
          { label: 'SFP', type: 'sfp', direction: 'input', count: 2 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['14-port', 'AVB/TSN', 'Dante optimized'],
      },
      {
        modelId: 'luminex-gc10',
        modelName: 'GigaCore 10',
        category: 'network-switch',
        rackUnits: 1,
        formFactor: 'half-rack',
        defaultPorts: [
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 8 },
          { label: 'SFP', type: 'sfp', direction: 'input', count: 2 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80, apiBasePath: '/api' },
        features: ['10-port', 'AVB/TSN', 'Compact', 'PoE optional'],
      },
    ],
  },

  // ─── Crestron ───────────────────────────────────────────────
  {
    id: 'crestron',
    displayName: 'Crestron',
    brandColor: '#263238',
    website: 'https://www.crestron.com',
    products: [
      {
        modelId: 'crestron-cp4n',
        modelName: 'CP4N',
        category: 'control-processor',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 2 },
          { label: 'USB', type: 'usb', direction: 'output', count: 2 },
        ],
        connectionInfo: { protocol: 'https', defaultPort: 443, notes: 'CIP TCP :41794 fallback' },
        features: ['4-series processor', '.NET runtime', 'HTML5 UI', 'Cresnet'],
        description: 'Enterprise control system processor.',
      },
      {
        modelId: 'crestron-dm-nvx-363',
        modelName: 'DM-NVX-363',
        category: 'encoder-decoder',
        rackUnits: 1,
        formFactor: 'half-rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 1 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 2 },
        ],
        connectionInfo: { protocol: 'https', defaultPort: 443 },
        features: ['4K60 AV-over-IP', 'DM NVX', 'USB routing', 'Dante 2-ch'],
      },
      {
        modelId: 'crestron-dm-md32x32',
        modelName: 'DM-MD32x32',
        category: 'matrix-switcher',
        rackUnits: 10,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'DM In', type: 'hdbaset', direction: 'input', count: 32 },
          { label: 'DM Out', type: 'hdbaset', direction: 'output', count: 32 },
        ],
        connectionInfo: { protocol: 'https', defaultPort: 443 },
        features: ['32x32 DM matrix', '4K60', 'HDBaseT', 'Audio breakaway'],
      },
      {
        modelId: 'crestron-tsw1070',
        modelName: 'TSW-1070',
        category: 'control-processor',
        rackUnits: 0,
        formFactor: 'desktop',
        defaultPorts: [
          { label: 'Ethernet PoE', type: 'ethernet', direction: 'input', count: 1 },
        ],
        connectionInfo: { protocol: 'https', defaultPort: 443 },
        features: ['10.1" touchscreen', 'HTML5 UI', 'PoE', 'Built-in mic/speaker'],
      },
    ],
  },

  // ─── Extron ─────────────────────────────────────────────────
  {
    id: 'extron',
    displayName: 'Extron',
    brandColor: '#1565c0',
    website: 'https://www.extron.com',
    products: [
      {
        modelId: 'extron-dtp-cp-108-4k',
        modelName: 'DTP CrossPoint 108 4K',
        category: 'matrix-switcher',
        rackUnits: 2,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 4 },
          { label: 'DTP In', type: 'hdbaset', direction: 'input', count: 6 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 2 },
          { label: 'DTP Out', type: 'hdbaset', direction: 'output', count: 6 },
        ],
        connectionInfo: { protocol: 'sis', defaultPort: 23, notes: 'SIS (Simple Instruction Set) over TCP' },
        features: ['10x8 matrix', '4K60', 'DTP extension', 'Audio DSP'],
        description: 'Scaling matrix switcher with DTP extension.',
      },
      {
        modelId: 'extron-in1808',
        modelName: 'IN1808',
        category: 'video-processor',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 6 },
          { label: 'DTP In', type: 'hdbaset', direction: 'input', count: 2 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 2 },
          { label: 'DTP Out', type: 'hdbaset', direction: 'output', count: 2 },
        ],
        connectionInfo: { protocol: 'sis', defaultPort: 23 },
        features: ['8x scaling presentation switcher', '4K60', 'PiP', 'Audio DSP'],
      },
      {
        modelId: 'extron-smp300',
        modelName: 'SMP 300',
        category: 'streaming-processor',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 1 },
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 1 },
          { label: 'Ethernet', type: 'ethernet', direction: 'output', count: 1 },
        ],
        connectionInfo: { protocol: 'sis', defaultPort: 23 },
        features: ['H.264 streaming', 'Dual recording', 'RTMP/RTSP', 'Scheduling'],
      },
      {
        modelId: 'extron-dxp84-hd4k',
        modelName: 'DXP 84 HD 4K',
        category: 'matrix-switcher',
        rackUnits: 1,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'HDMI In', type: 'hdmi', direction: 'input', count: 8 },
          { label: 'HDMI Out', type: 'hdmi', direction: 'output', count: 4 },
        ],
        connectionInfo: { protocol: 'sis', defaultPort: 23 },
        features: ['8x4 matrix', '4K60', 'EDID management', 'Audio embedding'],
      },
    ],
  },

  // ─── Ross ───────────────────────────────────────────────────
  {
    id: 'ross',
    displayName: 'Ross Video',
    brandColor: '#9c27b0',
    website: 'https://www.rossvideo.com',
    products: [
      {
        modelId: 'ross-carbonite-bp',
        modelName: 'Carbonite Black Plus',
        category: 'production-switcher',
        rackUnits: 3,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 24 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 16 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80 },
        features: ['2 M/E', '24 inputs', 'MultiViewer', 'UltraChrome'],
        description: 'Compact production switcher for live events.',
      },
      {
        modelId: 'ross-carbonite-ultra',
        modelName: 'Carbonite Ultra',
        category: 'production-switcher',
        rackUnits: 4,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI In', type: 'sdi', direction: 'input', count: 36 },
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 24 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80 },
        features: ['3 M/E', '36 inputs', '4K capable', 'XPression CG built-in'],
      },
      {
        modelId: 'ross-ultrix-fr5',
        modelName: 'Ultrix-FR5',
        category: 'matrix-switcher',
        rackUnits: 5,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI/IP In', type: 'sdi', direction: 'input', count: 80 },
          { label: 'SDI/IP Out', type: 'sdi', direction: 'output', count: 80 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80 },
        features: ['80x80 SDI/IP hybrid', 'SMPTE 2110', 'Built-in multiviewer', 'Softgear'],
        description: 'Hybrid SDI/IP router with integrated processing.',
      },
      {
        modelId: 'ross-xpression',
        modelName: 'XPression',
        category: 'graphics-processor',
        rackUnits: 4,
        formFactor: 'rack',
        defaultPorts: [
          { label: 'SDI Out', type: 'sdi', direction: 'output', count: 4 },
          { label: 'NDI Out', type: 'ndi', direction: 'output', count: 2 },
          { label: 'Ethernet', type: 'ethernet', direction: 'input', count: 2 },
        ],
        connectionInfo: { protocol: 'rest', defaultPort: 80 },
        features: ['Real-time 3D graphics', 'Multi-channel', 'Social media integration'],
        description: 'Real-time motion graphics and CG system.',
      },
    ],
  },
];

/** Flat list of all products across all manufacturers. */
export const ALL_CATALOG_PRODUCTS = CATALOG.flatMap((m) =>
  m.products.map((p) => ({ ...p, manufacturer: m.id, brandColor: m.brandColor, displayName: m.displayName }))
);
