/**
 * Store action unit tests.
 *
 * Strategy: Each test calls useStore.getState() to get the action functions and
 * reads state directly, then uses useStore.setState() to reset between tests so
 * every test is fully isolated from the shared initial state.
 *
 * We do NOT mock uuid — it is a pure JS library that works fine in Node/jsdom.
 * We DO mock the window fetch (persistence layer) so network calls don't leak
 * out of tests and don't cause noise.
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';
import { useStore } from '../index';
import type { Device, Rack } from '@/types';

// ============================================================
// Mock fetch so persistence flush-to-server calls don't error
// ============================================================
global.fetch = vi.fn().mockResolvedValue({ ok: true, json: async () => ({}) });

// ============================================================
// Helpers
// ============================================================

/** Build a minimal, valid device shape. */
function makeDevice(overrides: Partial<Device> = {}): Omit<Device, 'id'> {
  return {
    name: 'Test Device',
    manufacturer: 'blackmagic',
    model: 'Test Model',
    category: 'converter',
    status: 'online',
    rackUnits: 1,
    ports: [],
    health: { temperature: 30 },
    ...overrides,
  };
}

/** Build a minimal, valid rack shape (without id/slots — those are generated by addRack). */
function makeRack(overrides: Partial<Omit<Rack, 'id' | 'slots'>> = {}): Omit<Rack, 'id' | 'slots'> {
  return {
    name: 'Test Rack',
    location: 'Stage',
    width: 1,
    totalRU: 10,
    ...overrides,
  };
}

// ============================================================
// Reset store state between every test so tests are isolated
// ============================================================

/**
 * Capture a clean snapshot of the initial store state so we can
 * restore it cheaply between tests without re-importing the module.
 */
let initialSnapshot: ReturnType<typeof useStore.getState>;

beforeEach(() => {
  // On first run this captures the real initial state (with all mock devices/racks).
  // On subsequent runs we restore that snapshot.
  if (!initialSnapshot) {
    initialSnapshot = useStore.getState();
  } else {
    useStore.setState(initialSnapshot, true); // true = replace entire state
  }
  vi.clearAllMocks();
});

// ============================================================
// addRack / removeRack
// ============================================================

describe('addRack', () => {
  it('adds a rack with generated id and correct totalRU slots', () => {
    const { addRack } = useStore.getState();
    const rackSpec = makeRack({ totalRU: 5, width: 1 });
    const id = addRack(rackSpec);

    expect(typeof id).toBe('string');
    expect(id.length).toBeGreaterThan(0);

    const rack = useStore.getState().racks.find((r) => r.id === id);
    expect(rack).toBeDefined();
    expect(rack!.name).toBe('Test Rack');
    expect(rack!.totalRU).toBe(5);
    // Should have 5 slots (1 per RU for single-wide rack)
    expect(rack!.slots).toHaveLength(5);
  });

  it('creates all slots starting at RU 1 up to totalRU', () => {
    const { addRack } = useStore.getState();
    const id = addRack(makeRack({ totalRU: 3, width: 1 }));
    const rack = useStore.getState().racks.find((r) => r.id === id)!;
    const ruNumbers = rack.slots.map((s) => s.ru).sort((a, b) => a - b);
    expect(ruNumbers).toEqual([1, 2, 3]);
  });

  it('creates width * totalRU slots for multi-wide racks', () => {
    const { addRack } = useStore.getState();
    const id = addRack(makeRack({ totalRU: 4, width: 2 }));
    const rack = useStore.getState().racks.find((r) => r.id === id)!;
    // 2 columns x 4 RU each = 8 slots
    expect(rack!.slots).toHaveLength(8);
  });

  it('initialises all new slots with no deviceId', () => {
    const { addRack } = useStore.getState();
    const id = addRack(makeRack({ totalRU: 4 }));
    const rack = useStore.getState().racks.find((r) => r.id === id)!;
    rack.slots.forEach((s) => expect(s.deviceId).toBeUndefined());
  });
});

describe('removeRack', () => {
  it('removes the rack from the racks array', () => {
    const { addRack, removeRack } = useStore.getState();
    const id = addRack(makeRack());
    removeRack(id);
    const rack = useStore.getState().racks.find((r) => r.id === id);
    expect(rack).toBeUndefined();
  });

  it('clears rackId/rackSlot/rackColumn on devices that were in the removed rack', () => {
    const { addRack, addDevice, removeRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 5 }));
    const deviceId = addDevice(makeDevice({ rackId, rackSlot: 1, rackColumn: 0 }));

    removeRack(rackId);

    const device = useStore.getState().devices.find((d) => d.id === deviceId)!;
    expect(device.rackId).toBeUndefined();
    expect(device.rackSlot).toBeUndefined();
    expect(device.rackColumn).toBeUndefined();
  });

  it('does not affect devices in other racks', () => {
    const { addRack, addDevice, removeRack } = useStore.getState();
    const rackId1 = addRack(makeRack({ totalRU: 5 }));
    const rackId2 = addRack(makeRack({ totalRU: 5 }));
    const deviceId = addDevice(makeDevice({ rackId: rackId2, rackSlot: 1, rackColumn: 0 }));

    removeRack(rackId1);

    const device = useStore.getState().devices.find((d) => d.id === deviceId)!;
    expect(device.rackId).toBe(rackId2);
  });
});

// ============================================================
// addDevice / removeDevice
// ============================================================

describe('addDevice', () => {
  it('adds a device and returns a generated id', () => {
    const { addDevice } = useStore.getState();
    const id = addDevice(makeDevice({ name: 'New Device' }));
    expect(typeof id).toBe('string');
    const device = useStore.getState().devices.find((d) => d.id === id);
    expect(device).toBeDefined();
    expect(device!.name).toBe('New Device');
  });

  it('does not assign rack slots when device has no rackId', () => {
    const { addDevice } = useStore.getState();
    const id = addDevice(makeDevice({ name: 'Unassigned' }));
    const device = useStore.getState().devices.find((d) => d.id === id)!;
    expect(device.rackId).toBeUndefined();
  });

  it('assigns rack slot when device is added with rackId and rackSlot', () => {
    const { addRack, addDevice } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 5 }));
    const deviceId = addDevice(makeDevice({ rackId, rackSlot: 2, rackColumn: 0 }));

    const rack = useStore.getState().racks.find((r) => r.id === rackId)!;
    const slot = rack.slots.find((s) => s.ru === 2 && s.column === 0);
    expect(slot?.deviceId).toBe(deviceId);
  });
});

describe('removeDevice', () => {
  it('removes device from devices array', () => {
    const { addDevice, removeDevice } = useStore.getState();
    const id = addDevice(makeDevice());
    removeDevice(id);
    const found = useStore.getState().devices.find((d) => d.id === id);
    expect(found).toBeUndefined();
  });

  it('clears device from rack slots when removed', () => {
    const { addRack, addDevice, removeDevice } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 5 }));
    const deviceId = addDevice(makeDevice({ rackId, rackSlot: 1, rackColumn: 0 }));

    removeDevice(deviceId);

    const rack = useStore.getState().racks.find((r) => r.id === rackId)!;
    rack.slots.forEach((s) => expect(s.deviceId).toBeUndefined());
  });

  it('removes device from pin boards when removed', () => {
    const { addDevice, addPinBoardItem, removePinBoardItem: _, removeDevice } = useStore.getState();
    const deviceId = addDevice(makeDevice());
    const boardId = useStore.getState().pinBoards[0]?.id;
    if (!boardId) return; // No boards in state — skip

    useStore.getState().addPinBoardItem(boardId, {
      deviceId,
      position: { x: 0, y: 0 },
      size: { width: 200, height: 100 },
      showHealth: false,
      showTemperature: false,
      showPorts: false,
    });

    removeDevice(deviceId);

    const board = useStore.getState().pinBoards.find((b) => b.id === boardId)!;
    const item = board.items.find((i) => i.deviceId === deviceId);
    expect(item).toBeUndefined();
  });
});

// ============================================================
// assignDeviceToRack
// ============================================================

describe('assignDeviceToRack', () => {
  it('assigns a 1U device to the correct rack slot', () => {
    const { addRack, addDevice, assignDeviceToRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 10 }));
    const deviceId = addDevice(makeDevice({ name: 'SDI Converter', rackUnits: 1 }));

    assignDeviceToRack(deviceId, rackId, 3, 0);

    const device = useStore.getState().devices.find((d) => d.id === deviceId)!;
    expect(device.rackId).toBe(rackId);
    expect(device.rackSlot).toBe(3);
    expect(device.rackColumn).toBe(0);

    const rack = useStore.getState().racks.find((r) => r.id === rackId)!;
    const slot = rack.slots.find((s) => s.ru === 3 && s.column === 0)!;
    expect(slot.deviceId).toBe(deviceId);
  });

  it('assigns a 4U device filling 4 consecutive slots', () => {
    const { addRack, addDevice, assignDeviceToRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 10 }));
    const deviceId = addDevice(makeDevice({ name: 'Media Server', rackUnits: 4 }));

    assignDeviceToRack(deviceId, rackId, 2, 0); // slots 2–5

    const rack = useStore.getState().racks.find((r) => r.id === rackId)!;
    for (let ru = 2; ru <= 5; ru++) {
      const slot = rack.slots.find((s) => s.ru === ru && s.column === 0)!;
      expect(slot.deviceId).toBe(deviceId);
    }
    // Slot 1 and 6 should remain empty
    expect(rack.slots.find((s) => s.ru === 1 && s.column === 0)!.deviceId).toBeUndefined();
    expect(rack.slots.find((s) => s.ru === 6 && s.column === 0)!.deviceId).toBeUndefined();
  });

  it('clears old rack slots when device is moved to a new position', () => {
    const { addRack, addDevice, assignDeviceToRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 10 }));
    const deviceId = addDevice(makeDevice({ rackUnits: 1 }));

    // Place at slot 1, then move to slot 5
    assignDeviceToRack(deviceId, rackId, 1, 0);
    assignDeviceToRack(deviceId, rackId, 5, 0);

    const rack = useStore.getState().racks.find((r) => r.id === rackId)!;
    // Old slot 1 must be cleared
    expect(rack.slots.find((s) => s.ru === 1 && s.column === 0)!.deviceId).toBeUndefined();
    // New slot 5 must be assigned
    expect(rack.slots.find((s) => s.ru === 5 && s.column === 0)!.deviceId).toBe(deviceId);
  });

  it('can move a device from one rack to another', () => {
    const { addRack, addDevice, assignDeviceToRack } = useStore.getState();
    const rack1Id = addRack(makeRack({ totalRU: 5, name: 'Rack A' }));
    const rack2Id = addRack(makeRack({ totalRU: 5, name: 'Rack B' }));
    const deviceId = addDevice(makeDevice({ rackUnits: 1 }));

    assignDeviceToRack(deviceId, rack1Id, 1, 0);
    assignDeviceToRack(deviceId, rack2Id, 3, 0);

    const rack1 = useStore.getState().racks.find((r) => r.id === rack1Id)!;
    const rack2 = useStore.getState().racks.find((r) => r.id === rack2Id)!;

    // Old rack slot is empty
    expect(rack1.slots.find((s) => s.ru === 1)!.deviceId).toBeUndefined();
    // New rack slot is filled
    expect(rack2.slots.find((s) => s.ru === 3)!.deviceId).toBe(deviceId);

    const device = useStore.getState().devices.find((d) => d.id === deviceId)!;
    expect(device.rackId).toBe(rack2Id);
    expect(device.rackSlot).toBe(3);
  });

  it('assigns to column 0 by default when no column is specified', () => {
    const { addRack, addDevice, assignDeviceToRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 5 }));
    const deviceId = addDevice(makeDevice({ rackUnits: 1 }));

    // Intentionally omit the column argument
    assignDeviceToRack(deviceId, rackId, 2);

    const device = useStore.getState().devices.find((d) => d.id === deviceId)!;
    expect(device.rackColumn).toBe(0);
  });

  it('assigns device to column 1 in a 2-wide rack', () => {
    const { addRack, addDevice, assignDeviceToRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 5, width: 2 }));
    const deviceId = addDevice(makeDevice({ rackUnits: 1 }));

    assignDeviceToRack(deviceId, rackId, 1, 1);

    const rack = useStore.getState().racks.find((r) => r.id === rackId)!;
    const slotCol0 = rack.slots.find((s) => s.ru === 1 && s.column === 0)!;
    const slotCol1 = rack.slots.find((s) => s.ru === 1 && s.column === 1)!;
    expect(slotCol0.deviceId).toBeUndefined();
    expect(slotCol1.deviceId).toBe(deviceId);
  });

  it('does nothing when the deviceId does not exist in the store', () => {
    const { addRack, assignDeviceToRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 5 }));
    const racksBefore = useStore.getState().racks;

    assignDeviceToRack('nonexistent-device', rackId, 1, 0);

    // Racks should be unchanged (or same reference)
    const racksAfter = useStore.getState().racks;
    expect(racksAfter).toBe(racksBefore);
  });
});

// ============================================================
// removeDeviceFromRack
// ============================================================

describe('removeDeviceFromRack', () => {
  it('clears rackId, rackSlot, and rackColumn from the device', () => {
    const { addRack, addDevice, assignDeviceToRack, removeDeviceFromRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 5 }));
    const deviceId = addDevice(makeDevice({ rackUnits: 1 }));
    assignDeviceToRack(deviceId, rackId, 2, 0);

    removeDeviceFromRack(deviceId);

    const device = useStore.getState().devices.find((d) => d.id === deviceId)!;
    expect(device.rackId).toBeUndefined();
    expect(device.rackSlot).toBeUndefined();
    expect(device.rackColumn).toBeUndefined();
  });

  it('clears all rack slots occupied by the device', () => {
    const { addRack, addDevice, assignDeviceToRack, removeDeviceFromRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 10 }));
    // 3U device occupies slots 4, 5, 6
    const deviceId = addDevice(makeDevice({ rackUnits: 3 }));
    assignDeviceToRack(deviceId, rackId, 4, 0);

    removeDeviceFromRack(deviceId);

    const rack = useStore.getState().racks.find((r) => r.id === rackId)!;
    for (let ru = 4; ru <= 6; ru++) {
      expect(rack.slots.find((s) => s.ru === ru)!.deviceId).toBeUndefined();
    }
  });

  it('leaves the device in the devices array (only removes rack assignment)', () => {
    const { addRack, addDevice, assignDeviceToRack, removeDeviceFromRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 5 }));
    const deviceId = addDevice(makeDevice({ name: 'Still Exists' }));
    assignDeviceToRack(deviceId, rackId, 1, 0);

    removeDeviceFromRack(deviceId);

    const device = useStore.getState().devices.find((d) => d.id === deviceId);
    expect(device).toBeDefined();
    expect(device!.name).toBe('Still Exists');
  });
});

// ============================================================
// Multi-RU device placement (assign then verify slot coverage)
// ============================================================

describe('multi-RU device slot coverage', () => {
  it('4U device at slot 1 occupies slots 1–4 and leaves slot 5 empty', () => {
    const { addRack, addDevice, assignDeviceToRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 5 }));
    const deviceId = addDevice(makeDevice({ rackUnits: 4 }));
    assignDeviceToRack(deviceId, rackId, 1, 0);

    const rack = useStore.getState().racks.find((r) => r.id === rackId)!;
    for (let ru = 1; ru <= 4; ru++) {
      expect(rack.slots.find((s) => s.ru === ru)!.deviceId).toBe(deviceId);
    }
    expect(rack.slots.find((s) => s.ru === 5)!.deviceId).toBeUndefined();
  });

  it('two separate devices placed at different slots do not overlap', () => {
    const { addRack, addDevice, assignDeviceToRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 10 }));
    const deviceA = addDevice(makeDevice({ name: 'Device A', rackUnits: 2 }));
    const deviceB = addDevice(makeDevice({ name: 'Device B', rackUnits: 2 }));

    assignDeviceToRack(deviceA, rackId, 1, 0); // occupies 1–2
    assignDeviceToRack(deviceB, rackId, 3, 0); // occupies 3–4

    const rack = useStore.getState().racks.find((r) => r.id === rackId)!;
    expect(rack.slots.find((s) => s.ru === 1)!.deviceId).toBe(deviceA);
    expect(rack.slots.find((s) => s.ru === 2)!.deviceId).toBe(deviceA);
    expect(rack.slots.find((s) => s.ru === 3)!.deviceId).toBe(deviceB);
    expect(rack.slots.find((s) => s.ru === 4)!.deviceId).toBe(deviceB);
  });

  it('reassigning a multi-RU device clears all its previous slots', () => {
    const { addRack, addDevice, assignDeviceToRack } = useStore.getState();
    const rackId = addRack(makeRack({ totalRU: 10 }));
    const deviceId = addDevice(makeDevice({ rackUnits: 3 }));

    assignDeviceToRack(deviceId, rackId, 1, 0); // slots 1, 2, 3
    assignDeviceToRack(deviceId, rackId, 5, 0); // slots 5, 6, 7

    const rack = useStore.getState().racks.find((r) => r.id === rackId)!;
    // Old slots must be clear
    expect(rack.slots.find((s) => s.ru === 1)!.deviceId).toBeUndefined();
    expect(rack.slots.find((s) => s.ru === 2)!.deviceId).toBeUndefined();
    expect(rack.slots.find((s) => s.ru === 3)!.deviceId).toBeUndefined();
    // New slots must be set
    expect(rack.slots.find((s) => s.ru === 5)!.deviceId).toBe(deviceId);
    expect(rack.slots.find((s) => s.ru === 6)!.deviceId).toBe(deviceId);
    expect(rack.slots.find((s) => s.ru === 7)!.deviceId).toBe(deviceId);
  });
});

// ============================================================
// updateDeviceStatus / updateDeviceHealth
// ============================================================

describe('updateDeviceStatus', () => {
  it('updates the status field of a device', () => {
    const { addDevice, updateDeviceStatus } = useStore.getState();
    const id = addDevice(makeDevice({ status: 'online' }));
    updateDeviceStatus(id, 'error');
    const device = useStore.getState().devices.find((d) => d.id === id)!;
    expect(device.status).toBe('error');
  });

  it('does not affect other devices', () => {
    const { addDevice, updateDeviceStatus } = useStore.getState();
    const idA = addDevice(makeDevice({ name: 'A', status: 'online' }));
    const idB = addDevice(makeDevice({ name: 'B', status: 'online' }));
    updateDeviceStatus(idA, 'warning');
    const deviceB = useStore.getState().devices.find((d) => d.id === idB)!;
    expect(deviceB.status).toBe('online');
  });
});

describe('updateDeviceHealth', () => {
  it('updates health data for a device', () => {
    const { addDevice, updateDeviceHealth } = useStore.getState();
    const id = addDevice(makeDevice());
    updateDeviceHealth(id, { temperature: 75, cpuUsage: 90 });
    const device = useStore.getState().devices.find((d) => d.id === id)!;
    expect(device.health.temperature).toBe(75);
    expect(device.health.cpuUsage).toBe(90);
  });

  it('optionally updates status when health is updated', () => {
    const { addDevice, updateDeviceHealth } = useStore.getState();
    const id = addDevice(makeDevice({ status: 'online' }));
    updateDeviceHealth(id, { temperature: 80 }, 'warning');
    const device = useStore.getState().devices.find((d) => d.id === id)!;
    expect(device.status).toBe('warning');
  });

  it('does not change status when optional status arg is omitted', () => {
    const { addDevice, updateDeviceHealth } = useStore.getState();
    const id = addDevice(makeDevice({ status: 'online' }));
    updateDeviceHealth(id, { temperature: 55 });
    const device = useStore.getState().devices.find((d) => d.id === id)!;
    expect(device.status).toBe('online');
  });
});
